---

# Default 'latest' version
- name: Windows | Install puppet-agent from Puppetlabs repository
  win_package:
    path: http://downloads.puppetlabs.com/windows/puppet{{ puppet_version }}/puppet-agent-x64-latest.msi
    product_id: Puppet Agent (64-bit)
    creates_service: puppet
    state: present
  when: puppet_agent_package_name == "puppet-agent"


# Customized version
- name: Windows | Install puppet-agent from Puppetlabs repository
  win_package:
    path: http://downloads.puppetlabs.com/windows/puppet{{ puppet_version }}/{{ puppet_agent_package_name }}-x64.msi
    product_id: Puppet Agent (64-bit)
    creates_service: puppet
    state: present
  when: puppet_agent_package_name != "puppet-agent"

- name: Windows | Puppet-agent service
  win_service:
    name: puppet
    start_mode: auto
    state: started
