---

# lvm_vg_setup:
# - vgname: data
#   disks:
#     - /dev/xvdb
#     - /dev/xvdc
#     - /dev/xvdd
#     - /dev/xvde
#   lvname: vgdata
#   lvsize: 100%FREE
#   # Defines additional lvcreate options (e.g. stripes, stripesize, etc)
#   lvopts: '-i4 -I64'
#   # Defines filesystem to format lvol as
#   filesystem: xfs
#   # Defines if filesystem should be mounted
#   mount: true
#   # Defines mountpoint for lvol
#   mountpoint: /data
#   # Defines additional mount options (e.g. noatime, noexec, etc)
#   mountopts: 'noatime'
# - vgname: archive
#   disks:
#     - /dev/xvdf
#   lvname: vgarchive
#   lvsize: 100%FREE
#   # Defines additional lvcreate options (e.g. stripes, stripesize, etc)
#   lvopts: ''
#   # Defines filesystem to format lvol as
#   filesystem: ext4
#   # Defines if filesystem should be mounted
#   mount: true
#   # Defines mountpoint for lvol
#   mountpoint: /archive
#   # Defines additional mount options (e.g. noatime, noexec, etc)
#   mountopts: 'noatime'


# Defines if LVM will be managed by role
# default is false to ensure nothing is changed by accident.
manage_lvm: false